export const ADD_CARD = 'ADD_CARD'
export const DELETE_CARD = 'DELETE_CARD'
export const LIKE = 'LIKE'
export const GET_CARDS = 'GET_CARDS'
export const CURRENT_USER = 'CURRENT_USER'
export const USER_LIKE = 'USER_LIKE'
